# ==== pytest ====
[tool.pytest.ini_options]

# ==== Coverage ====
[tool.coverage.run]

# ==== black ====
[tool.black]
line-length = 119
target-version = ['py311']

# ==== isort ====
[tool.isort]
profile = "black"
line_length = 119
known_first_party = ["dsf"]
skip = ["venv/"]


# ==== mypy ====
[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = []
